### ISSUE TITLE
Fix Jandex indexing for 'other' modules

### ISSUE THREAD

**Issue by logscape** [liquidlabsio/precognito#8]
Warning:
16:29:00.228 [build-32] WARN  io.quarkus.deployment.steps.ReflectiveHierarchyStep - Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- io.precognito.search.Search
**Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.**

Solution:
https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module

**Comment by bluemonk3y** [comment]
soted!
